In [6]:
import pandas as pd

pd.read_excel('dados_tratados/curva_abc_geral.xlsx')

,Unnamed: 0,Cód.Produto,Descrição,Curva Geral,Qtde Venda Geral,Dias Pedido Geral,Média por dia Geral,Capacid.Chão,Estoque Chão,Ativ.Ressupr. Geral,...,Permite Frac.,Ender.Cx.Fechada,Embal.,Capacidade Cx,Estoque Cx,Apanha Frac,Ender.Fracionado,Tipo,Capacidade Frac,Estoque Frac
0,0,106011,NARIDRIN 12 HORAS FR C/30ML,A,1148435.0,271.0,4237.7675,3500.0,2835.0,1353.0,...,Não,010-018-01-02,100.0,30.0,28,Sim,18.903,Ponta De G,500.0,381.0
1,1,231012,EXPEC XAROPE FR C/120ML,A,342057.0,199.0,1718.8794,1020.0,625.0,536.0,...,Não,014-028-01-02,60.0,5.0,0,Sim,29.086,Flowrack,240.0,18.0
2,2,101190,EMSEXPECTOR XPE 120ML,A,246096.0,177.0,1390.3729,960.0,293.0,429.0,...,Não,014-040-01-01,60.0,4.0,0,Sim,29.075,Flowrack,240.0,88.0
3,3,101175,INFRALAX C/ 15 COMP,A,173121.0,268.0,645.9739,1584.0,1205.0,634.0,...,Não,014-032-02-01,48.0,36.0,32,Sim,25.081,Flowrack,384.0,311.0
4,4,102138,INFRALAX C/30 COMP,A,163324.0,267.0,611.7004,1824.0,1167.0,559.0,...,Não,014-042-02-01,48.0,30.0,17,Sim,29.081,Flowrack,480.0,422.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8940,8940,130073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Não,NaN,60.0,0.0,0,Não,NaN,NaN,0.0,0.0
8941,8941,421840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Não,018-001-01-02,96.0,1.0,0,Sim,10.066,Flowrack,96.0,0.0
8942,8942,316036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Não,018-004-01-02,100.0,2.0,0,Não,NaN,NaN,0.0,0.0
8943,8943,11211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Não,018-001-01-01,60.0,2.0,0,Sim,11.103,Prateleira,120.0,0.0
8944,8944,29909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Não,NaN,60.0,0.0,0,Não,NaN,NaN,0.0,0.0

In [3]:
curva_geral.Curva.value_counts()

C    1019
B     612
A     407
Name: Curva, dtype: int64

In [4]:
curva_geral.Curva.value_counts(normalize = True)

C    0.500000
B    0.300294
A    0.199706
Name: Curva, dtype: float64

In [5]:
curva_geral.Curva.value_counts(normalize = True) * 100

C    50.000000
B    30.029441
A    19.970559
Name: Curva, dtype: float64

In [6]:
frequencia = curva_geral.Curva.value_counts()

In [7]:
percentual = curva_geral.Curva.value_counts(normalize = True) * 100

In [10]:
dist_freq_curva = pd.DataFrame({'Frequência' : frequencia, 'Percentual (%)' : percentual})

In [11]:
dist_freq_curva

   Frequência  Percentual (%)
C        1019       50.000000
B         612       30.029441
A         407       19.970559

In [12]:
dist_freq_curva.rename_axis('Curva', axis = 'columns', inplace = True)

In [13]:
dist_freq_curva

Curva  Frequência  Percentual (%)
C            1019       50.000000
B             612       30.029441
A             407       19.970559